import type { Metadata } from "next"
import "./globals.css"
import "@mantine/core/styles.css"
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core"
import { LanguageProvider } from "./LanguageContext"
import { LanguageSwitcher } from "./LanguageSwitcher"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body>
        <ColorSchemeScript />
        <LanguageProvider>
          <MantineProvider>
            <LanguageSwitcher />
            {children}
          </MantineProvider>
        </LanguageProvider>
      </body>
    </html>
  )
}
