export { layout } from "@/config/content/layout"
export { hero } from "@/config/content/hero"
export { about } from "@/config/content/about"
export { techStack } from "@/config/content/tech-stack"
export { certifications } from "@/config/content/certifications"
export { projects } from "@/config/content/projects"
export { faq } from "@/config/content/faq"
export { footer } from "@/config/content/footer"
